### ISSUE TITLE
Dependency installation via Dashboard message needs status indicator

### ISSUE THREAD

**Issue by raamdev** [websharks/woocommerce-s2member-x#2]
When installing the s2Member X plugin on a site that does not have any of the dependencies installed, several Dashboard messages will appear in succession presenting you with a link to install WP Sharks Core and then WooCommerce.

![2016-05-25_10-20-50](https://cloud.githubusercontent.com/assets/53005/15545811/a7b7bdae-226b-11e6-8479-eed4a6629ace.png)

However, when you click the link to install, there is no indication that something is happening other than your browser appearing to be connecting to something (presumably loading another page). 

If the process takes longer than what you're used to waiting when loading web pages, you start to think  that something is wrong and the instinct is to refresh the page or try again (which in this case would be the wrong thing to do and would totally break the intended workflow).

What we need is a JS indicator that shows that something is happening, something that turns the "Click here to install '[software]'" link into "Installing..." with a little spinning indictor, just like on the WordPress plugins page when updating a plugin inline:

![plugin-update-inline](https://cloud.githubusercontent.com/assets/53005/15546464/0d2572f6-226e-11e6-8efe-cd7389445f0d.gif)

**Comment by raamdev** [comment]
@jaswsinc Let me know if this is a WP-PHP-RV issue; if so, I'll open a cross-issue over there.

**Comment by jaswrks** [comment]
Ah.. Thanks! Yeah, I noticed this too whenever I was testing locally. I think it's a problem in WordPress core actually. The underlying problem is that whenever I was testing locally the PHP script did not flush enough output for the page to change and for WordPress to display the status of what was happening as would normally be expected. I'm not sure exactly what causes this locally yet though.

> Let me know if this is a WP-PHP-RV issue; if so, I'll open a cross-issue over there.

I'd call this a WP Sharks Core issue, so if you'd like to move it there I think that would be better. When this is corrected, it will change in the WP Sharks Core repo, and in the WP Sharks Core RV repo.
- https://github.com/websharks/wp-sharks-core
- https://github.com/websharks/wp-sharks-core-rv

**Comment by Lifeischoice** [comment]
S2member x and x-pro are coming? hooray...Congratulations folks...well deserved.

**Comment by jaswrks** [comment]
@Lifeischoice Thank you. Yes, they are coming soon. Still a work-in-progress.

**Comment by jaswrks** [comment]
Closing in favor of https://github.com/websharks/wp-sharks-core/issues/1

**Comment by Lifeischoice** [comment]
Is it too early to ask for any eta? Also, let me know if you'll need beta testers...will be glad to help.
